---
title: "Why APIs"
description: |
  You're probably not using APIs, but you probably should. What are APIs? How do you use them? And how do you get started?
site: distill::distill_website
---

```{r embed-xaringan, echo=FALSE, fig.cap="[Slides](slides/slides.html)"}
xaringanExtra::embed_xaringan(url = "slides/slides.html", ratio = "4:3")
```
  
### Our demo API:

* See it on RStudio Connect: https://colorado.rstudio.com/rsc/coin_api/

* Interact directly in your browser: 
  * single coin toss: https://colorado.rstudio.com/rsc/coin_api/coin_toss
  * multi coin toss: https://colorado.rstudio.com/rsc/coin_api/multi_toss?n=40 (change parameter n to conduct a different number of tosses)


### Additional Resources:

* See the `plumber` package website: https://www.rplumber.io/. You’ll find installation instructions along with related projects and contextual information

* Watch our webinar covering the latest in the Plumber package: https://rstudio.com/resources/webinars/expanding-r-horizons-integrating-r-with-plumber-apis/

* At our annual conference rstudio::conf 2020, Alex Gold (Solutions Engineer at RStudio) presented some additional ways to bring your R work into production using Plumber: https://rstudio.com/resources/rstudioconf-2020/deploying-end-to-end-data-science-with-shiny-plumber-and-pins/

* Another excellent conference talk is James Blair's rstudio::conf 2019 talk "Democratizing R with Plumber APIS" where he takes an existing Shiny application that uses an R model and turns the model into an API so it can be used by other applications: https://rstudio.com/resources/rstudioconf-2019/democratizing-r-with-plumber-apis/  

* If you’re interested in how Plumber specifically works with RStudio Connect you can find documentation here: https://docs.rstudio.com/how-to-guides/rsc/publish-plumberapi/